#########################################################################################
# SpringBoot Settings
#########################################################################################
spring:
  profiles:
    activate:
      on-profile: test
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    hikari: jdbc-url= jdbc:h2:mem:edcb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
#########################################################################################
# Tomcat Settings
#########################################################################################
server:
  port: 8081
#########################################################################################
# File Path Information Settings
#########################################################################################
file:
  resourcePath: C:/dev/edc-batch/resources/
  rootPath: C:/dev/hdata/
  attachRootPath: C:/dev/app_nas/anl_data/
  logDirName: ht_log001m
  tempDirName: temp
  dataFilePrefixName: ht_
  dataFileExtension: txt
  attachDirName:
    opd: BA204/opendart
    kot: BA201/kotra
#########################################################################################
# Batch Scheduler(Cron) Information Settings
#########################################################################################
scheduler:
  biz:
    isActive: false
    cron: "0 45 15 * * ?"
    baseline: D-1
  big:
    isActive: false
    cron: "0 40 15 * * ?"
    baseline: D-1
  som:
    isActive: false
    cron: "30 2 14 * * ?"
    baseline: D-1
  saf:
    isActive: false
    cron: "* 0 07 * * ?"
    baseline: D-1
  nav:
    isActive: false
    cron: "0 10 12 * * ?"
    baseline: D-4
  kot:
    isActive: false
    cron: "0 10 12 * * ?"
    baseline: D-1
  opd:
    isActive: false
    cron: "0 10 12 * * ?"
    baseline: D-1
  uct:
    isActive: true
#    cron: "0 0 07-23 1-14 * ?"
    cron: "0-30 54 17 * * ?"
    baseline: Y-1