#########################################################################################
# SpringBoot Settings
#########################################################################################
spring:
  profiles:
    activate:
      on-profile: prod.monthly
server:
  port: 8081 # Tomcat Port
logging:
    config: classpath:log4j2-prod.monthly.xml
#########################################################################################
# Batch Job Information Settings
#########################################################################################
job:
  info:
    biz: # bizinfo.go.kr
      cron: "0 20 01 * * ?" # 매일 01:20
      isActive: false
      cycle: daily
      baseline: D-1
      period: 1
      nodes:
        - biz001m # 기업마당 최신공고
    big: # tools.kinds.or.kr
      cron: "0 0 02 * * ?" # 매일 02:00
      isActive: false
      cycle: daily
      baseline: D-1
      period: 1
      nodes:
        - big001m # 빅카인즈 뉴스검색
        - big002m # 빅카인즈 이슈 랭킹
        - big003m # 빅카인즈 워드클라우드
        - big004m # 빅카인즈 뉴스 타임라인
    som: # Somtrend 서비스 종료
      cron: "30 2 14 * * ?"
      isActive: false
      cycle: daily
      baseline: D-1
      period: 1
      nodes:
        - som001m
        - som002m
        - som003m
        - som004m
        - som005m
    saf: # saftykorea.kr
      cron: "0 30 01 * * ?" # 매일 01:30
      isActive: false
      cycle: daily
      baseline: D-1
      period: 1
      nodes:
        - saf001m # 국가기술표준원 제품안전정보센터 제품안전정보
        - saf001l # 국가기술표준원 제품안전정보센터 제품안전정보 파생모델
        - saf002l # 국가기술표준원 제품안전정보센터 제품안전정보 연관인증번호 목록
        - saf003l # 국가기술표준원 제품안전정보센터 제품안전정보 제조공장 목록
        - saf004l # 국가기술표준원 제품안전정보센터 제품안전정보 인증 이미지 목록
    nav: # cafe.naver.com
      cron: "0 10 01 * * ?" # 매일 01:10
      isActive: false
      cycle: daily
      baseline: D-4
      period: 1
      nodes:
        - nav003m # 네이버카페 나이키매니아 판맴데이터
        - nav004m # 네이버카페 중고나라 판매데이터
    kot: # apis.data.go.kr
      cron: "0 40 02 * * ?" # 매일 02:40
      isActive: false
      cycle: daily
      baseline: D-1
      period: 7
      nodes:
        - kot001m # KOTRA 대한무역투자진흥공사 해외시장 뉴스 수집
        - kot002m # KOTRA 대한무역투자진흥공사 해외시장 뉴스 키워드 수집
    opd: # opendart.fss.or.kr
      cron: "0 0 03 * * ?" # 매일 03:00
      isActive: false
      cycle: daily
      baseline: D-1
      period: 1
      nodes:
        - opd001m # OpenDart 기업 개황 정보 수집
        - opd002m # OpenDart 기업 공시내역 수집
    uct: # comtrade.un.org
      cron: "0 0 06 1 * ?" # 매월 1일 06:00
      isActive: true
      cycle: monthly
      baseline: Y-1
      period: 2
      nodes:
        - uct001m # UN Comtrade 수출데이터
    com: # 공통 배치 (파일관련)
      cron: "0 0 05 1 * ?" # 매월 1일 05:00
      isActive: true
      cycle: monthly
      baseline: M-2
#########################################################################################
# File Path Information Settings
#########################################################################################
file:
  resourcePath: /data/edc-batch/prod/resources/ # 리소스파일 경로
  dataRootPath: /hdata/ # 데이터파일 루트경로
  dataFilePrefixName: ht_ # 테이블명 접두어
  dataFileExtension: txt # 파일 확장자
  logDirName: ht_log001m # 로그파일 디렉토리명
  tempDirName: temp # 임시파일 디렉토리명
  backupDirName: backup # 백업파일 디렉토리명
  cleanBackupBaseDt: -2 # 백업폴더 삭제 매월1일에 전전월달 폴더 삭제
  attachRootPath: /app_nas/anl_data/ # 첨부파일 루트경로
  attachDirName:
    opd: BA204/opendart # OpenDart 첨부파일 디렉토리명
    kot: BA201/kotra # Kotra 첨부파일 디렉토리명