#########################################################################################
# SpringBoot Settings
#########################################################################################
spring:
  profiles:
    activate:
      on-profile: test
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    hikari: jdbc-url= jdbc:h2:mem:edcb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
#########################################################################################
# Tomcat Settings
#########################################################################################
server:
  port: 8080
#########################################################################################
# File Path Information Settings
#########################################################################################
file:
  resourcePath: C:/dev/edc-batch/resources/
  rootPath: C:/dev/hdata/
  attachRootPath: C:/dev/app_nas/anl_data/
  logDirName: ht_log001m
  tempDirName: temp
  dataFilePrefixName: ht_
  dataFileExtension: txt
  attachDirName:
    opd: BA204/opendart
    kot: BA201/kotra
#########################################################################################
# Batch Scheduler(Cron) Information Settings
#########################################################################################
scheduler:
  jobs:
    biz:
      isActive: false
      cron: "0 45 15 * * ?"
      cycle: DAILY
      baseline: D-1
      period: 1
    big:
      isActive: true
      cron: "0 40 15 * * ?"
      cycle: DAILY
      baseline: D-1
      period: 7
    som:
      isActive: false
      cron: "30 2 14 * * ?"
      cycle: DAILY
      baseline: D-1
      period: 1
    saf:
      isActive: false
      cron: "* 0 07 * * ?"
      cycle: DAILY
      baseline: D-1
      period: 1
    nav:
      isActive: false
      cron: "0 10 12 * * ?"
      cycle: DAILY
      baseline: D-4
      period: 1
    kot:
      isActive: false
      cron: "0 10 12 * * ?"
      cycle: DAILY
      baseline: D-1
      period: 7
    opd:
      isActive: false
      cron: "0 10 12 * * ?"
      cycle: DAILY
      baseline: D-1
      period: 1
    uct:
      isActive: true
      #    cron: "0 0 07-23 1-14 * ?"
      cron: "0-30 54 17 * * ?"
      cycle: MONTHLY
      baseline: Y-1
      period: 2